apiVersion: 1
groups:
  - orgId: 1
    name: group-1m
    folder: alerts
    interval: 1m
    rules:
      - uid: ee6lkovnpbapsc
        title: Significant Deviation in Successful Payments
        condition: D
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              datasource:
                type: prometheus
                # uid: PBFA97CFB590B2093
              editorMode: code
              expr: |-
                (sum(increase(payments_successful_total[24h])) - avg_over_time(sum(increase(payments_successful_total[24h]))[7d:]))
                / avg_over_time(sum(increase(payments_successful_total[24h]))[7d:]) > 0.15
              instant: false
              interval: ""
              intervalMs: 15000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: D
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              datasource:
                type: prometheus
                # uid: PBFA97CFB590B2093
              editorMode: code
              expr: |-
                (sum(increase(payments_successful_total[24h])) - avg_over_time(sum(increase(payments_successful_total[24h]))[7d:]))
                / avg_over_time(sum(increase(payments_successful_total[24h]))[7d:]) < -0.15
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: D
        dashboardUid: ce6hwqg2misqob
        panelId: 1
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          __dashboardUid__: ce6hwqg2misqob
          __panelId__: "1"
          description: These alerts monitor significant deviations in the number of successful payments over the last 24 hours compared to the weekly average (over the last 7 days).
          summary: |-
            Significant Drop in Successful Payments
            This alert triggers when successful payments decrease by more than 15%, potentially indicating:
                Failures in the payment processing system.
                A sudden drop in user activity.
                Issues with external dependencies like payment gateways.

            Significant Increase in Successful Payments
            This alert triggers when successful payments increase by more than 15%, possibly signaling:
                A spike in user activity due to promotions or events.
                Potential errors causing duplicate or incorrect transactions.
                Unusual traffic patterns or system behavior changes.
        labels: {}
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
